### ISSUE TITLE
Get original file/extension of uploaded file

### ISSUE THREAD

**Issue by naglalakk** [haskell-servant/servant-multipart#16]
Hi. Is there a way I can fetch the .extension and original filename of the file being uploaded?
When I upload a file it goes into a temporary folder 
`/var/folders/hy/c7smkw390xl71sdqgxz80pth0000gn/T/servant-multipart79683-1.buf`

I understand that I can change this pattern and the location of the temporary folder. But I fail to see how I can include the original name of the file and the extension.

**Comment by alpmestan** [comment]
Well, the idea is that this file is temporary (it gets removed after the request has been processed) so it's not a problem that the name isn't all that intelligible. 

The original name of the file is however available to you. If you look at [`MultipartData`](https://hackage.haskell.org/package/servant-multipart-0.11.1/docs/Servant-Multipart.html#t:MultipartData), you can see that it contains a `files` field, of type [`FileData tag`](https://hackage.haskell.org/package/servant-multipart-0.11.1/docs/Servant-Multipart.html#t:FileData). As you can see in the documentation for that data type (and its fields), you can find there:

- what would be the `<input>`'s name, in the HTML form
- the original name of the file, on the client's disk
- its content type
- the path to the (temporary) uploaded file that you should move some place else if you want to keep it (if using the `Tmp` backend) or the actual content of the file as a bytestring (if using the `Mem` backend)

So `fdFileName` is the piece of information you're looking for here.

**Comment by naglalakk** [comment]
ahh ok I see now. So I would just add a name field to my data type and then I can just do this

```
instance FromMultipart Tmp Image where
    fromMultipart multipartData =
        Image <$> fmap fdPayload (lookupFile "image" multipartData)
              <*> fmap fdFileName (lookupFile "image" multipartData)
              <*> (optional $ lookupInput "description" multipartData)
              <*> (optional Nothing)
```
And then in the handler I can switch out the temporary path with my own path ++ name. 
I think I understand now. Thank you very much for your reply @alpmestan

**Comment by naglalakk** [comment]
Thank you got this working like this. Closing this issue 👍

**Comment by alpmestan** [comment]
Exactly. Glad you figured it out :)
