### ISSUE TITLE
Proper response after max file size is exceeded

### ISSUE THREAD

**Issue by michalrus** [haskell-servant/servant-multipart#9]
WAI developers decided to do `error "Maximum size exceeded"` here:

https://github.com/yesodweb/wai/blob/a1cb17ff79887e0c33be7fb975b5a0f559e2cf45/wai-extra/Network/Wai/Parse.hs#L634

Which ends up as `500 Internal Server Error` instead of the correct `413 Payload Too Large`.

What can we do here? A custom `Network.Wai.Handler.Warp.setOnExceptionResponse` that matches that error text? :sob: :sob: :sob: Have mercy!

**Comment by alpmestan** [comment]
@michalrus I think the right fix is one that would involve removing this from wai, and have it throw the right error instead. Would you mind taking this issue over to wai's repo and see what they say?

In the meantime, if you have an immediate fix to make servant-multipart behave as expected, I think the library will have mercy and eat that patch, at least until wai is fixed. Sounds good?

**Comment by michalrus** [comment]
:arrow_up: :smiley_cat:

**Comment by alpmestan** [comment]
Thanks! Let's see what the wai developers say and change servant-multipart accordingly.

**Comment by michalrus** [comment]
Hopefully, no change here will be needed. :)

**Comment by afcady** [comment]
After the bug's first birth anniversary you should  do the error text matching.

**Comment by michalrus** [comment]
Haha, what I’m doing in our corporate code is handle this on Nginx’ side. I think this is the proper solution, as the transfer will be dropped as soon as possible.

It would be nice to have this working here, though.

Such 413 request doesn’t even get to Servant:

```nix
{
    services.nginx.httpConfig = ''

            # [...]

            location ~ ^/v1/user/[^/]+/profile/image$ {
              client_max_body_size ${toString config.backend.profileImages.maxSize};
              ${proxyPassBackend}
            }

            error_page 413 @err413;
            location @err413 {
              default_type application/json;
              return 413 '{"data":{},"code": "PayloadTooLarge","description": "Supplied payload is too large."}';
            }

            # [...]

        '';
}
```

**Comment by jonathanjouty** [comment]
Is this issue fixed now that https://github.com/yesodweb/wai/issues/647 seems to have been?

**Comment by alpmestan** [comment]
@jonathanjouty Hello! :-)

Yes, servant-server applications built against a wai/warp versions that have the fix should do the right thing.
